#!/bin/bash

## Full installation ###########################
#singularity pull docker://dfam/tetools:latest
################################################

#SBATCH -J RepeatM
#SBATCH -o ~/Elephant_project/mEleMax1/repeat/%x.%j.out
#SBATCH -e ~/Elephant_project/mEleMax1/repeat/%x.%j.err

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
##SBATCH -w b004
#SBATCH --qos=standard
#SBATCH --cpus-per-task=12
#SBATCH --mem=48G
#SBATCH --time=3-00:00:00

module load singularity



## Only change this: ############################################
OUT_DIR="~/Elephant_project/mEleMax1/repeat"
ASSEMBLY="~/Elephant_project/mEleMax1/intermediates/bionano/l2/l2_s1.fa"
ASSEMBLY_NAME=$(basename $ASSEMBLY .${ASSEMBLY##*.})
SPECIES_NAME='Elephas maximus'
#################################################################


echo "=== 1/5. Indexing genome for RepeatModeler  ======================================="

mkdir -p "${OUT_DIR}/01_modeler"
cd "${OUT_DIR}/01_modeler"
ln -s $ASSEMBLY ${ASSEMBLY_NAME}.fa
singularity exec --bind ~/:~/ ~/Software/tetools_latest.sif \
BuildDatabase -name ${ASSEMBLY_NAME} ${ASSEMBLY_NAME}.fa


echo "=== 2/5. Starting RepeatModeler  =================================================="

srun \
singularity exec --bind ~/:~/ ~/Software/tetools_latest.sif \
RepeatModeler -database ${ASSEMBLY_NAME} -pa ${SLURM_CPUS_PER_TASK} -LTRStruct


echo "=== 3/5. Combining repeats library  ==============================================="

mkdir -p "${OUT_DIR}/02_libraries"
cd "${OUT_DIR}/02_libraries"
srun \
singularity exec --bind ~/:~/ --pwd /opt/RepeatMasker/Libraries/ ~/Software/tetools_latest.sif \
famdb.py -i RepeatMaskerLib.h5 families --format fasta_name --include-class-in-name --ancestors --descendants "${SPECIES_NAME}" > ${ASSEMBLY_NAME}-rm.fa

cat ${ASSEMBLY_NAME}-rm.fa "${OUT_DIR}/01_modeler/${ASSEMBLY_NAME}" > "${ASSEMBLY_NAME}_combined.fa"


echo "=== 4/5. Starting RepeatMasker  ==================================================="

mkdir -p "${OUT_DIR}/03_masker"
cd "${OUT_DIR}/03_masker"
ln -s $ASSEMBLY ${ASSEMBLY_NAME}.fa
srun \
singularity exec --bind ~/:~/ ~/Software/tetools_latest.sif \
RepeatMasker -pa ${SLURM_CPUS_PER_TASK} -a -s -gccalc -xsmall -lib "${OUT_DIR}/02_libraries/${ASSEMBLY_NAME}-rm.fa" ${ASSEMBLY_NAME}.fa


echo "=== 5/5. Plotting results  ========================================================"

srun \
singularity exec --bind ~/:~/ ~/Software/tetools_latest.sif \
calcDivergenceFromAlign.pl -s ${ASSEMBLY_NAME}.align.divsum -a ${ASSEMBLY_NAME}.align_with_div ${ASSEMBLY_NAME}.align

VAR="$(grep -n total ${ASSEMBLY_NAME}.tbl| cut -f1 -d:)"
SIZE="$(sed -n $VAR\p ${ASSEMBLY_NAME}.tbl | sed -e 's/ /\t/g' | cut -f3)"

srun \
singularity exec --bind ~/:~/ ~/Software/tetools_latest.sif \
createRepeatLandscape.pl -div ${ASSEMBLY_NAME}.align.divsum -g ${SIZE} > ${ASSEMBLY_NAME}.align.divsum.html
