#!/bin/bash

#SBATCH -J fastqc
#SBATCH -o ../stdout/fastqc.%j.out
#SBATCH -e ../stderr/fastqc.%j.err

#SBATCH --mail-type=ALL
#SBATCH --mail-user=..@..

#SBATCH --partition=begendiv,main
#SBATCH --qos=standard
#SBATCH --cpus-per-task=8
#SBATCH --mem=8G
#SBATCH --time=8:00:00

module load FastQC/0.11.9-Java-11

fastqc -t 8 -f fastq -o ../Elephant_project/VGP/evaluation/FastQC/ ../Elephant_project/VGP/transcriptomic_data/*.gz
