#!/bin/bash

#SBATCH -J arima.bam2bed
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=2
#SBATCH --mem=2G
#SBATCH --time=12:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env

echo
echo "== 13/14. Converting BAM to BED ===="
cd $OUT_DIR
bamToBed -i "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.FINAL.bam" > "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.FINAL.bed"
echo "== Done! ===="
