#!/bin/bash

#SBATCH -J arima.map1
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=24
#SBATCH --mem=32G
#SBATCH --time=08:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env

echo
echo "== 3/12. Making BWA alignment of forward HiC reads ===="

cd $OUT_DIR
srun \
bwa-mem2 mem -t 16 "${OUT_DIR}/idx/${ASSEMBLY_NAME}" $HIC_FQ_1 | samtools view -@ 8 -b > "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads_1.bam"

echo "== Done! ===="

