#!/bin/bash

#SBATCH -J bedSort
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=4
#SBATCH --mem=48G
#SBATCH --time=12:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env

echo
echo "== 2/2. Sorting BED by read name ===="
cd $OUT_DIR
sort -k 4 "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.FINAL.bed" > "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.FINAL.sorted.bed"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.FINAL.bed"
echo "== Done! ===="
