#!/bin/bash

#SBATCH -J arima.index1

#SBATCH --mail-type=END,FAIL

#SBATCH --cpus-per-task=2
#SBATCH --mem=48G
#SBATCH --time=12:00:00


ASSEMBLY_NAME=$(basename $SCAFFOLDS .${SCAFFOLDS##*.})

echo
echo "(This is the Arima Genomics' mapping pipeline starting...)"

echo
echo "== 1/11. Making reference index ===="
cd "${OUT_DIR}/idx"
ln -s $ASSEMBLY "${ASSEMBLY_NAME}.fa"
samtools faidx "${ASSEMBLY_NAME}.fa"
echo "== Done! ===="
