#!/bin/bash

#SBATCH -J arima.index1
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=2
#SBATCH --mem=72G
#SBATCH --time=3:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env

echo
echo "(This is the Arima Genomics' mapping pipeline starting...)"

echo
echo "== 1/12. Making reference index ===="

cd "${OUT_DIR}/idx"
ln -s $ASSEMBLY "${ASSEMBLY_NAME}.fa"
srun \
samtools faidx "${ASSEMBLY_NAME}.fa"

echo "== Done! ===="

echo
echo "== 2/12. Making BWA index ===="

cd "${OUT_DIR}/idx"
srun \
bwa-mem2 index -p $ASSEMBLY_NAME "${ASSEMBLY_NAME}.fa"

echo "== Done! ===="
