
#!/bin/bash

#SBATCH -J arima.clean
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=01:00:00


echo
echo "== 14/14. Removing intermediate files  ===="
cd $OUT_DIR
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads_1.bam"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads_2.bam"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered_1.bam"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered_2.bam"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.bam"
rm "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads.filtered.semifinal.bam"
