#!/bin/bash

#SBATCH -J arima.map1
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=24
#SBATCH --mem=64G
#SBATCH --time=1-00:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env
module load Boost/1.67.0-foss-2018b

echo
echo "== 3/11. Making BWA alignment of forward HiC reads ===="
cd $OUT_DIR
bwa-mem2 mem -t 16 "${OUT_DIR}/idx/${ASSEMBLY_NAME}" $HIC_FQ_1 | samtools view -@ 8 -b > "${OUT_DIR}/${ASSEMBLY_NAME}_HiCreads_1.bam"
echo "== Done! ===="

