#!/bin/bash

#SBATCH -J arima.index1
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=1:00:00

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate ARIMA_env
module load Boost/1.67.0-foss-2018b

echo
echo "(This is the Arima Genomics' mapping pipeline starting...)"

echo
echo "== 1/12. Making reference index ===="

cd "${OUT_DIR}/idx"
ln -s $ASSEMBLY "${ASSEMBLY_NAME}.fa"
srun \
samtools faidx "${ASSEMBLY_NAME}.fa"

echo "== Done! ===="
