#!/bin/bash

#SBATCH -J trimNs

#SBATCH --mail-type=FAIL,END

#SBATCH --cpus-per-task=1
#SBATCH --mem=12G
#SBATCH --time=1-00:00:00 

cd 
#cat mEleMax1_Saphyr_DLE1_3680720_bppAdjust_cmap_l3_108_purged_36_108_fa_NGScontigs_HYBRID_SCAFFOLD_NCBI.fasta > l3_combined.fa ; cat mEleMax1_Saphyr_DLE1_3680720_bppAdjust_cmap_l3_108_purged_36_108_fa_NGScontigs_HYBRID_SCAFFOLD_NOT_SCAFFOLDED.fasta >> l3_combined.fa

cd /scratch/ddepanis/Software/bionano/trimNs

#python3 remove_fake_cut_sites_DNAnexus.py /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/hybrid_scaffolds/l3_combined.fa /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.fa /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.log

#python3 trim_Ns_DNAnexus.py /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.fa /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.list

python3 clip_regions_DNAnexus.py /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.fa /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/fakeCuts.list  /scratch/ddepanis/Elephant_project/mEleMax1/intermediates/bionano/l3/l3_s1.fa
~                                                                             
