#!/bin/bash

#SBATCH -J trimNs
#SBATCH --mail-type=END,FAIL
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --time=01:00:00 

export PATH="${CONDA_BIN_DIR}:${PATH}"
source activate bionano

cd ${OUT_DIR}/${ASSEMBLY_NAME}/${ASSEMBLY_NAME}/hybrid_scaffolds

cat *NGScontigs_HYBRID_SCAFFOLD_NCBI.fasta > bionano_combined.fa ; cat *NGScontigs_HYBRID_SCAFFOLD_NOT_SCAFFOLDED.fasta >> bionano_combined.fa

cd ${OUT_DIR}/${ASSEMBLY_NAME}/${ASSEMBLY_NAME}

python3 ${BIONANO_FILES_DIR}/remove_fake_cut_sites_DNAnexus.py hybrid_scaffolds/bionano_combined.fa fakeCuts.fa fakeCuts.log

python3 ${BIONANO_FILES_DIR}/trim_Ns_DNAnexus.py fakeCuts.fa fakeCuts.list

python3 ${BIONANO_FILES_DIR}/clip_regions_DNAnexus.py fakeCuts.fa fakeCuts.list ${ASSEMBLY_NAME}_s1.fa
